gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    return_expiration: true
    single_use: false
    cookie:
        enabled: true
        remove_token_from_body: false
        http_only: true
        same_site: strict
        secure: true
        path: /
        domain: null

when@dev:
    gesdinet_jwt_refresh_token:
        cookie:
            secure: false