lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 7200

    token_extractors:
        cookie:
            enabled: true
            name: BEARER

    set_cookies:
        BEARER:
            samesite: strict

    remove_token_from_body_when_cookies_used: false

when@dev:
    lexik_jwt_authentication:
        set_cookies:
            BEARER:
                secure: false