# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    messenger: true
    filter_sets:

        # name our filter set "my_thumb_filter"
        palia_item_icon:
            filters:
                downscale:
                    max: [ 80, 80 ]
        palia_character_avatar:
            filters:
                downscale:
                    max: [ 96, 96 ]
        palia_character_illustration:
            filters:
                relative_resize:
                    widen: 960
        enshrouded_item_icon_96:
            filters:
                downscale:
                    max: [ 96, 96 ]
        enshrouded_item_icon_48:
            filters:
                downscale:
                    max: [ 48, 48 ]
        enshrouded_item_icon_24:
            filters:
                downscale:
                    max: [ 24, 24 ]
        960x540:
            quality: 80
            filters:
                fixed:
                    width: 960
                    height: 540
        384x216:
            quality: 80
            filters:
                fixed:
                    width: 384
                    height: 216