nelmio_api_doc:
    documentation:
        info:
            title: Le Bus Magique
            description: API du Bus Magique
            version: 1.0.0
        components:
            schemas:
                error:
                    type: object
                    properties:
                        code:
                            type: integer
                        message:
                            type: string
            responses:
                UnauthorizedError:
                    description: "Identifiants invalides"
                    content:
                        application/json:
                            schema:
                                allOf: [ $ref: '#/components/schemas/error' ]
                BadRequest:
                    description: "Requête invalide"
                    content:
                        application/json:
                            schema:
                                allOf: [ $ref: '#/components/schemas/error' ]
                JwtTokenInvalid:
                    description: "Token JWT invalide, expiré ou introuvable"
                    content:
                        application/json:
                            schema:
                                allOf:
                                    - $ref: '#/components/schemas/error'
        paths:
            /api/login:
                post:
                    tags:
                        - Authentication
                    description: Se connecter à l'API, retourne une date d'expiration.
                    requestBody:
                        content:
                            application/json:
                                schema:
                                    type: object
                                    example:
                                        username: 'john@doe.ext'
                                        password: 'MySecr3tPassword!@'
                    responses:
                        '200':
                            description: Connexion réussie, retourne la date d'expiration et créé 2 cookies (BEARER et refresh_token).
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            refresh_token_expiration:
                                                type: integer
                        '401':
                            $ref: '#/components/responses/UnauthorizedError'

            /api/register:
                post:
                    tags:
                        - Authentication
                    description: "Créer un compte pour un nouvel utilisateur."
                    requestBody:
                        content:
                            application/json:
                                schema:
                                    type: object
                                    example:
                                        email: 'john@doe.ext'
                                        nickname: 'JohnDoe'
                                        password: 'MySecr3tPassword!@'
                    responses:
                        '201':
                            description: Confirmation de la création du compte.
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            code:
                                                type: integer
                                            message:
                                                type: string
                        '409':
                            description: Adresse e-mail et/ou pseudonyme déjà utilisés
            /api/logout:
                get:
                    tags:
                        - Authentication
                    description: "Déconnexion de l'utilisateur connecté."

            /api/user/genshin/map/marker:
                post:
                    tags:
                        - Genshin
                    description: Ajouter (add) ou retirer (remove) un marqueur de l'utilisateur connecté.
                    requestBody:
                        content:
                            application/json:
                                schema:
                                    type: object
                                    example:
                                        map: 'teyvat'
                                        action: 'add'
                                        marker: 5
                    responses:
                        '200':
                            description: Action réalisée avec succès.
                        '400':
                            $ref: '#/components/responses/BadRequest'
                        '401':
                            $ref: '#/components/responses/UnauthorizedError'
    areas:
        path_patterns:
            - ^/api(?!/doc$)