vich_uploader:
    db_driver: orm

    mappings:
        genshin_map_icon:
            uri_prefix: /uploads/genshin/maps/icons
            upload_destination: '%kernel.project_dir%/public/uploads/genshin/maps/icons'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
