vich_uploader:
    db_driver: orm

    mappings:
        genshin_map_icon:
            uri_prefix: /uploads/api/genshin/maps/icons
            upload_destination: '%kernel.project_dir%/public/uploads/api/genshin/maps/icons'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        genshin_map_media:
            uri_prefix: /uploads/api/genshin/maps/medias
            upload_destination: '%kernel.project_dir%/public/uploads/api/genshin/maps/medias'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        palia_item_icon:
            uri_prefix: /uploads/api/palia/items
            upload_destination: '%kernel.project_dir%/public/uploads/api/palia/items'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        palia_currency_icon:
            uri_prefix: /uploads/api/palia/currencies
            upload_destination: '%kernel.project_dir%/public/uploads/api/palia/currencies'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        palia_skill_icon:
            uri_prefix: /uploads/api/palia/skills
            upload_destination: '%kernel.project_dir%/public/uploads/api/palia/skills'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        palia_character_avatar:
            uri_prefix: /uploads/api/palia/characters/avatars
            upload_destination: '%kernel.project_dir%/public/uploads/api/palia/characters/avatars'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        palia_character_illustration:
            uri_prefix: /uploads/api/palia/characters/illustrations
            upload_destination: '%kernel.project_dir%/public/uploads/api/palia/characters/illustrations'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        enshrouded_item_icon:
            uri_prefix: /uploads/api/enshrouded/items
            upload_destination: '%kernel.project_dir%/public/uploads/api/enshrouded/items'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        enshrouded_npc_icon:
            uri_prefix: /uploads/api/enshrouded/npcs
            upload_destination: '%kernel.project_dir%/public/uploads/api/enshrouded/npcs'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        enshrouded_map_icon:
            uri_prefix: /uploads/api/enshrouded/map/icons
            upload_destination: '%kernel.project_dir%/public/uploads/api/enshrouded/map/icons'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        enshrouded_map_marker_image:
            uri_prefix: /uploads/api/enshrouded/map/images
            upload_destination: '%kernel.project_dir%/public/uploads/api/enshrouded/map/images'
            namer: Vich\UploaderBundle\Naming\UniqidNamer