vich_uploader:
    db_driver: orm

    mappings:
        genshin_map_icon:
            uri_prefix: /uploads/api/genshin/maps/icons
            upload_destination: '%kernel.project_dir%/public/uploads/api/genshin/maps/icons'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        genshin_map_media:
            uri_prefix: /uploads/api/genshin/maps/medias
            upload_destination: '%kernel.project_dir%/public/uploads/api/genshin/maps/medias'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
